# Generated by Django 3.1.7 on 2021-02-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
